Address ApplicationTests::QueryLogsTest errors
This commit addresses the following test errors since #52392

```ruby
$ bin/test test/application/query_logs_test.rb:271
Run options: --seed 33207

E

Error:
ApplicationTests::QueryLogsTest#test_controller_and_namespaced_controller_are_named_correctly,_legacy:
NoMethodError: undefined method `update_formatter' for module ActiveRecord::QueryLogs
    /home/yahonda/src/github.com/rails/rails/activerecord/lib/active_record/railtie.rb:403:in `block (2 levels) in <class:Railtie>'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:77:in `each'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
    lib/rails/application/finisher.rb:94:in `block in <module:Finisher>'
    lib/rails/initializable.rb:32:in `instance_exec'
    lib/rails/initializable.rb:32:in `run'
    lib/rails/initializable.rb:61:in `block in run_initializers'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `call'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
    lib/rails/initializable.rb:60:in `run_initializers'
    lib/rails/application.rb:428:in `initialize!'
    /home/yahonda/src/github.com/rails/rails/tmp/d20240723-41340-lvtci5/app/config/environment.rb:5:in `<top (required)>'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
    /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
    test/application/query_logs_test.rb:291:in `boot_app'
    test/application/query_logs_test.rb:276:in `block in <class:QueryLogsTest>'

bin/test test/application/query_logs_test.rb:271

Finished in 4.038127s, 0.2476 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```